### ============================================
### NOTIFICATIONS UPDATE NOTIFICATION
### ============================================

### Test
POST {baseUrl}/notifications-update-notification
Authorization: Bearer {token}
Content-Type: application/json

{
  "test": "data"
}
