### ============================================
### CONTRACTS UPDATE CONTRACT
### ============================================

### Test
POST {baseUrl}/contracts-update-contract
Authorization: Bearer {token}
Content-Type: application/json

{
  "test": "data"
}
