### ============================================
### CONTRACTS DELETE CONTRACT
### ============================================

### Test
POST {baseUrl}/contracts-delete-contract
Authorization: Bearer {token}
Content-Type: application/json

{
  "test": "data"
}
