### ============================================
### VENUES CREATE VENUE
### ============================================

### Test
POST {baseUrl}/venues-create-venue
Authorization: Bearer {token}
Content-Type: application/json

{
  "test": "data"
}
