### ============================================
### VENUES GET VENUE
### ============================================

### Test
GET {baseUrl}/venues-get-venue
Authorization: Bearer {token}
Content-Type: application/json

{
  "test": "data"
}
