### ============================================
### CONTRACTS GET CONTRACT
### ============================================

### Test
GET {baseUrl}/contracts-get-contract
Authorization: Bearer {token}
Content-Type: application/json

{
  "test": "data"
}
